# Pytorch  

let's revisit the most important aspects of pytorch

In [1]:
import torch

## Tensors

Why use Tensors over Numpy's ndarrays?

Answer: Tensors are 
1. can run on GPUs, meaning operations can be parallelized
2. optimized for automatic differentiation, making it extra fast for neural networks and gradient descent.

### Initializing a Tensor

#### tensors can be created directly from data.

In [2]:
data = [[0,1], [2,3]]
x_data = torch.tensor(data)

#### made from numpy array

In [4]:
import numpy as np

In [6]:
rng = np.random.default_rng(47)
data2 = rng.random((3,3,3))
x_data2 = torch.from_numpy(data2)
x_data2

tensor([[[0.7418, 0.7537, 0.4652],
         [0.1037, 0.9669, 0.3208],
         [0.2003, 0.8578, 0.5131]],

        [[0.1792, 0.7505, 0.7930],
         [0.5538, 0.8217, 0.6109],
         [0.4337, 0.3103, 0.7144]],

        [[0.9022, 0.1936, 0.6102],
         [0.0615, 0.5511, 0.1124],
         [0.7556, 0.9543, 0.9451]]], dtype=torch.float64)

#### made from another tensor

In [8]:
x_ones = torch.ones_like(x_data2)
print(f"The ones tensors: \n {x_ones} \n")

x_rand = torch.rand_like(x_data2)
print(f"Random tensor: \n {x_rand} \n")

x_zeros = torch.zeros_like(x_data2)
print(f"Zeros tensor: \n {x_zeros} \n")

The ones tensors: 
 tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]], dtype=torch.float64) 

Random tensor: 
 tensor([[[0.6881, 0.2798, 0.2454],
         [0.3671, 0.2802, 0.8426],
         [0.3099, 0.2003, 0.1388]],

        [[0.3988, 0.5412, 0.2563],
         [0.3526, 0.6160, 0.8600],
         [0.9232, 0.7339, 0.5448]],

        [[0.4339, 0.1516, 0.4243],
         [0.7505, 0.8758, 0.0394],
         [0.9511, 0.6238, 0.2189]]], dtype=torch.float64) 

Zeros tensor: 
 tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64) 



### Tensor Attributes

to know the properties/attributes of a tensor there are a couple of pytorch helpful methods

In [18]:
tensor =  torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Number of dimensions of tensor: {tensor.ndim}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

## you can change device tensor is stored on using this

tensor = tensor.to(device=torch.device('cuda'))

print(f"New device for tensor is: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Number of dimensions of tensor: 2
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
New device for tensor is: cuda:0


### Operations on Tensors

there are a lot of operations on tensors, which we don't have to revise all of them now

#### Joining Tensors

concatenate sequence of tensors along a dimension

In [ ]:
tensor2 = torch.rand(1,2)

tensor2

tensor([[0.4728, 0.2257]])

In [ ]:
## horizontal stacking
tensor2_horizontal = torch.cat([tensor2, tensor2, tensor2], dim=1)
print(tensor2_horizontal)

tensor([[0.4728, 0.2257, 0.4728, 0.2257, 0.4728, 0.2257]])


In [ ]:
## vertical stacking
tensor2_vertical = torch.cat([tensor2, tensor2, tensor2], dim=0)
print(tensor2_vertical)

tensor([[0.4728, 0.2257],
        [0.4728, 0.2257],
        [0.4728, 0.2257]])


#### Arithmetic

some arithmetic operations include matrix multiplication usin `@`, `matmul`

In [36]:
tensor_np = rng.integers(10, size=(3,3))
tensor1 = torch.from_numpy(tensor_np)
tensor2 = torch.from_numpy(rng.integers(10, size=(3,2)))
print(f"Tensor1: \n {tensor1}")
print(f"Tensor2: \n {tensor2}")

Tensor1: 
 tensor([[4, 2, 0],
        [6, 9, 5],
        [4, 0, 7]])
Tensor2: 
 tensor([[1, 5],
        [7, 5],
        [1, 5]])


In [38]:
## the matrix multiplication
y1 = tensor1 @ tensor2
y2 = tensor1.matmul(tensor2)
print(f"y1: \n {y1}")
print(f"y2: \n {y2}")

y1: 
 tensor([[ 18,  30],
        [ 74, 100],
        [ 11,  55]])
y2: 
 tensor([[ 18,  30],
        [ 74, 100],
        [ 11,  55]])


another one is element-wise multiplication

In [39]:
y3 = tensor1 * tensor1
y4 = tensor1.mul(tensor1)
print(f"y3: \n {y3}")
print(f"y4: \n {y4}")

y3: 
 tensor([[16,  4,  0],
        [36, 81, 25],
        [16,  0, 49]])
y4: 
 tensor([[16,  4,  0],
        [36, 81, 25],
        [16,  0, 49]])
